CREATE TABLE data_barang_now (
  `id` INT PRIMARY KEY,
  `tanggal_perolehan` DATE,
  `asset` VARCHAR(255),
  `kode_fa_fams` VARCHAR(255),
  `nama_barang` VARCHAR(255),
  `outlet_pencatatan` VARCHAR(255),
  `outlet_actual` VARCHAR(255),
  `type_barang` VARCHAR(255),
  `location` VARCHAR(255),
  `jabatan` VARCHAR(255),
  `nama_user` VARCHAR(255),
  `nik` VARCHAR(255),
  `komputer_nama` VARCHAR(255),
  `ip_address` VARCHAR(255),
  `kondisi` VARCHAR(255),
  `keterangan` VARCHAR(255),
  `serial_number` VARCHAR(255),
  `sophos` VARCHAR(255),
  `landesk` VARCHAR(255),
  `capex_or_selisih` VARCHAR(255),
  `created_at` DATETIME,
  `updated_at` DATETIME,
  `area_user` VARCHAR(255)
);

CREATE TABLE data_barang (
  `id` INT PRIMARY KEY,
  `tanggal_perolehan` DATE,
  `asset` VARCHAR(255),
  `kode_fa_fams` VARCHAR(255),
  `nama_barang` VARCHAR(255),
  `outlet_pencatatan` VARCHAR(255),
  `outlet_actual` VARCHAR(255),
  `type_barang` VARCHAR(255),
  `location` VARCHAR(255),
  `jabatan` VARCHAR(255),
  `nama_user` VARCHAR(255),
  `nik` VARCHAR(255),
  `komputer_nama` VARCHAR(255),
  `ip_address` VARCHAR(255),
  `kondisi` VARCHAR(255),
  `keterangan` VARCHAR(255),
  `serial_number` VARCHAR(255),
  `sophos` VARCHAR(255),
  `landesk` VARCHAR(255),
  `capex_or_selisih` VARCHAR(255),
  `bulan` VARCHAR(50),
  `tahun` VARCHAR(10),
  `created_at` DATETIME,
  `updated_at` DATETIME,
  `area_user` VARCHAR(255)
);

CREATE TABLE mutasi_now (
  `asset` VARCHAR(255),
  `kode_fa` VARCHAR(255),
  `nama_barang` VARCHAR(255),
  `outlet_actual` VARCHAR(255),
  `type_barang` VARCHAR(255),
  `location` VARCHAR(255),
  `jabatan` VARCHAR(255),
  `user_domain` VARCHAR(255),
  `nik` VARCHAR(255),
  `komputer_nama` VARCHAR(255),
  `ip_address` VARCHAR(255),
  `kondisi` VARCHAR(255),
  `keterangan` VARCHAR(255),
  `serial_number` VARCHAR(255),
  `sophos` VARCHAR(255),
  `landesk` VARCHAR(255),
  `mutasi_asal` VARCHAR(255),
  `mutasi_tujuan` VARCHAR(255),
  `keterangan_mutasi` VARCHAR(255),
  `area_user` VARCHAR(255)
);

CREATE TABLE mutasi (
  `asset` VARCHAR(255),
  `kode_fa` VARCHAR(255),
  `nama_barang` VARCHAR(255),
  `outlet_actual` VARCHAR(255),
  `type_barang` VARCHAR(255),
  `location` VARCHAR(255),
  `jabatan` VARCHAR(255),
  `user_domain` VARCHAR(255),
  `nik` VARCHAR(255),
  `komputer_nama` VARCHAR(255),
  `ip_address` VARCHAR(255),
  `kondisi` VARCHAR(255),
  `keterangan` VARCHAR(255),
  `serial_number` VARCHAR(255),
  `sophos` VARCHAR(255),
  `landesk` VARCHAR(255),
  `mutasi_asal` VARCHAR(255),
  `mutasi_tujuan` VARCHAR(255),
  `keterangan_mutasi` VARCHAR(255),
  `bulan` VARCHAR(50),
  `tahun` VARCHAR(10),
  `area_user` VARCHAR(255)
);

CREATE TABLE penghapusan_now (
  `id` INT PRIMARY KEY,
  `tanggal_perolehan` DATE,
  `asset` VARCHAR(255),
  `kode_fa_fams` VARCHAR(255),
  `nama_barang` VARCHAR(255),
  `acquis_val` DOUBLE,
  `accum_dep` DOUBLE,
  `book_val` DOUBLE,
  `outlet_pencatatan` VARCHAR(255),
  `outlet_actual` VARCHAR(255),
  `type_barang` VARCHAR(255),
  `location` VARCHAR(255),
  `jabatan` VARCHAR(255),
  `nama_user` VARCHAR(255),
  `nik` VARCHAR(255),
  `komputer_nama` VARCHAR(255),
  `ip_address` VARCHAR(255),
  `kondisi` VARCHAR(255),
  `keterangan` VARCHAR(255),
  `serial_number` VARCHAR(255),
  `sophos` VARCHAR(255),
  `landesk` VARCHAR(255),
  `area_user` VARCHAR(255)
);

CREATE TABLE penghapusan (
  `id` INT PRIMARY KEY,
  `tanggal_perolehan` DATE,
  `asset` VARCHAR(255),
  `kode_fa_fams` VARCHAR(255),
  `nama_barang` VARCHAR(255),
  `acquis_val` DOUBLE,
  `accum_dep` DOUBLE,
  `book_val` DOUBLE,
  `outlet_pencatatan` VARCHAR(255),
  `outlet_actual` VARCHAR(255),
  `type_barang` VARCHAR(255),
  `location` VARCHAR(255),
  `jabatan` VARCHAR(255),
  `nama_user` VARCHAR(255),
  `nik` VARCHAR(255),
  `komputer_nama` VARCHAR(255),
  `ip_address` VARCHAR(255),
  `kondisi` VARCHAR(255),
  `keterangan` VARCHAR(255),
  `serial_number` VARCHAR(255),
  `sophos` VARCHAR(255),
  `landesk` VARCHAR(255),
  `bulan` VARCHAR(50),
  `tahun` VARCHAR(10),
  `area_user` VARCHAR(255)
);

